
  # This was auto generated by ./mk_environment.sh on Feb-21-2008 
  #  [Version  $Id: mk_environment.sh,v 1.31 2007/08/31 19:11:19 claude Exp $  ]
  #    NOTE:  each time ./mk_environment.sh is run this file gets flattened
  #           That is in an effort to 'update' what might 
  #           have been missing the first time around
  
###  ROOT OF MASTER QUARANTINE [ OLDER ]
###
###       bulding ontop of an exsisting quarantine? place its environemtn here
####################################################################################
#   source /data/nih/nih1/quarantine_NIH_F/environment

###  ROOT OF SUBORDINATE QUARANTINE [ NEWER ]
###
###        If you are using a quarantine hyerachie specify the one with updates here
####################################################################################
   export ROOT=/data/noel/noel4/Feb-14-2008

###  PATH
###
###        This is best with as little in it as possible
####################################################################################
# only = for sh
   if [  "Linux"m = "IRIX64"m ] ; then
     export PATH="${NOELSOFT_DIR}/DTIAnalysis/bdti/Progs/:/data/noel/noel6/Oct-2010/bin/:/usr/local/perl5.8/bin/:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/bsd:/usr/bin/X11:/usr/local/bin/X11":$PATH
   else
     export PATH="${NOELSOFT_DIR}/DTIAnalysis/bdti/Progs/:/data/noel/noel6/Oct-2010/bin/:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/X11/bin":$PATH
   fi

###  LD LIRARY 32 PATH
###
###        if you have installed libraries you might need to have them in your environment
####################################################################################
  if [ -z $LD_LIBRARYN32_PATH ] ;then  
    export LD_LIBRARYN32_PATH="/data/noel/noel6/Oct-2010/lib/:/usr/local/lib/"
  else
    export LD_LIBRARYN32_PATH="/data/noel/noel6/Oct-2010/lib/:/usr/local/lib/:"$LD_LIBRARYN32_PATH
  fi


###  LD LIRARY PATH
###
###        if you have installed libraries you might need to have them in your environment
####################################################################################

  if [ -z $LD_LIBRARY_PATH ]; then   
   export LD_LIBRARY_PATH="/data/noel/noel6/Oct-2010/lib"
  else
   export LD_LIBRARY_PATH=$LD_LIBRARY_PATH":/data/noel/noel6/Oct-2010/lib"
  fi


###   MNI DATA PATH 
###
###            { why fix what isn't implemented :}
###             Agaist all of my suggestions this is/has become[ing] obsolete
####################################################################################
 if [ -z $MNI_DATAPATH ] ;then  
  export MNI_DATAPATH="/data/noel/noel6/Oct-2010/share:/data/noel/noel6/Oct-2010/data:/usr/local/mni/data"
 else
   export MNI_DATAPATH="/data/noel/noel6/Oct-2010/share:/data/noel/noel6/Oct-2010/data:/usr/local/mni/data:"$MNI_DATAPATH
 fi


### PERL LIB
###
###       [IMHO  perl should also be a part of the quarantine  ] 
####################################################################################
 if [ -z  $PERL5LIB ] ;then  
   export PERL5LIB="/data/noel/noel6/Oct-2010/perl:/data/noel/noel6/Oct-2010/lib/mni_autoreg"
 else
   export PERL5LIB="/data/noel/noel6/Oct-2010/perl:/data/noel/noel6/Oct-2010/lib/mni_autoreg:"$PERL5LIB
 fi

### R LIBS
###
####################################################################################
 if [ -z $R_LIBS ] ; then  
   export R_LIBS="/data/noel/noel6/Oct-2010/R_LIBS"
 else
   export R_LIBS="/data/noel/noel6/Oct-2010/R_LIBS:"$R_LIBS
 fi


### SET PROMPT STUFF 
###
####################################################################################
  #  If you want some funky prompt when running in the Q 
  # set prompt="Quarantine--Oct-04-05:\n %n@%m [%/] "
  # set prompt="QENV: %n@%m [%/] "


  export VOLUME_CACHE_THRESHOLD=-1

  
  # MINC-2 options
  export MINC_FORCE_V2=0
  export MINC_COMPRESS=4

  # Source the SGE environment"

  echo "Sourcing SGE environment..."
  source /usr/sge/default/common/settings.sh